name: Trigger HTTP Request on Push or Pull Request

on:
  push:
  pull_request:

jobs:
  trigger-http-request:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Make an HTTP request
      - name: Trigger HTTP request
        run: |
          # Replace this with your desired URL
          URL="http://172.16.43.249:9122/ext/api/v2/processService/running?processServiceId=2448745516712192&accessKey=rYlwhLmN&signature=yXURFJRoGmWvfO89HW0cfoT8GnQ%3D&signatureMethod=1.0"
          
          # Send the HTTP request using curl
          RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $URL)
          
          # Print the HTTP status code
          echo "HTTP Status Code: $RESPONSE"

          # Fail the workflow if the HTTP request fails (status code other than 200)
          if [ "$RESPONSE" -ne 200 ]; then
            echo "HTTP request failed with status code $RESPONSE"
            exit 1
          else
            echo "HTTP request was successful"
          fi
